---
# default topic name is this machine's hostname
# this is to ensure that every RC has its own topic and AMQP account
environment: production

communication:
  url: amqp://labwiki.test.atlantis.ugent.be

resources:
- type: node
  uid: <%= Socket.gethostname %>
